
dkbuild-apacheconf:
  package_name: dkbuild_apacheconf
  deps:
    - dkfileutils
    - jinja2
    - future
  devdeps:
    - pytest
    - dk-tasklib:
        deps:
          - invoke >= 0.22
          - PyYAML == 3.11
          - dkfileutils >= 1.3.0
          - watchdog >= 0.8.3
          - twine >= 1.9.1
          - dkpkg >= 1.0.0
